apiVersion: kubauth.kubotal.io/v1alpha1
kind: OidcClient
metadata:
  name: okdp-app
  namespace: okdp-system
spec:
  displayName: "OKDP Console"
  description: "OIDC client for the OKDP control-plane console"
  public: true
  entryURL: "https://console.okdp.dev-sandbox"
  accessTokenLifespan: 1h0m0s
  idTokenLifespan: 1h0m0s
  refreshTokenLifespan: 1h0m0s
  redirectURIs:
    - "https://console.okdp.dev-sandbox/"
    - "https://console.okdp.dev-sandbox"
    - "https://console.okdp.dev-sandbox/silent-refresh.html"
  postLogoutURL: "https://console.okdp.dev-sandbox"
  grantTypes:
    - "authorization_code"
    - "refresh_token"
  responseTypes:
    - "id_token"
    - "code"
    - "token"
    - "id_token token"
    - "code id_token"
    - "code token"
    - "code id_token token"
  scopes:
    - "openid"
    - "profile"
    - "email"
    - "groups"
    - "offline_access"
  forceOpenIdScope: true
